# Generated by Django 2.0.5 on 2018-07-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180716_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'set_book_as_returned'), ('can_view_loaned_books', 'view_loaned_books'))},
        ),
    ]
